image: node:lts

before_script:
  - npm ci

deploy-prod:
  stage: deploy
  script:
    - npm run build
    - mkdir public
    - cp -r ./dist/* public/
  artifacts:
    paths:
      - public
  environment: production
  only:
    - main